### ISSUE TITLE
New customer jsp page to be redesigned in super admin perspective

### ISSUE THREAD

**Issue by iqshayori** [iquesters/oms#5]

**Comment by iqsayantan** [comment]
@iqshayori @iqsam started working on new customer jsp page.

**Comment by iqshayori** [comment]
@iqsayantan: Please let know what is the status of this particular issue and a tentative date for its completion

**Comment by iqsam** [comment]
@iqshayori @iqsayantan had already informed me, this will have to be extended to Sunday (12/04/2015) EOD. I am changing the milestone date.

**Comment by iqsam** [comment]
@iqsayantan what is the status?

**Comment by iqsayantan** [comment]
This issue is resolved with the commit id : 897099e4f1e10d42d98fe4c46f36b4c5bcafe300

@iqsam Please incorporate following update statement in UMS_OPTION table

UPDATE UMS_OPTION SET OPTION_LINK=cust/search&serviceName=GetNewCustomer WHERE  OPTION_ID=26;

@iqsam Please review the code

**Comment by iqshayori** [comment]
Tested and issue is fixed, so closing the issue.
