### ISSUE TITLE
Search customer jsp page to be redesigned in super admin perspective

### ISSUE THREAD

**Issue by iqshayori** [iquesters/oms#6]

**Comment by iqsam** [comment]
@iqsayantan what is the status?

**Comment by iqsayantan** [comment]
This issue is resolved with the commit id :897099e4f1e10d42d98fe4c46f36b4c5bcafe300

@iqsam Please incorporate following UPDATE statement into UMS_OPTION db

UPDATE UMS_OPTION SET OPTION_LINK=cust/search&serviceName=GetNewCustomer WHERE  OPTION_ID=27;

@iqsam Please review the code

**Comment by iqshayori** [comment]
Tested and issue is fixed, so closing this issue.
